# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab3/lab3_pynq_z2.xdc

# Block Designs: bd/soc_sys/soc_sys.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_sys || ORIG_REF_NAME==soc_sys} -quiet] -quiet

# IP: bd/soc_sys/ip/soc_sys_processing_system7_0_0/soc_sys_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_sys_processing_system7_0_0 || ORIG_REF_NAME==soc_sys_processing_system7_0_0} -quiet] -quiet

# IP: bd/soc_sys/ip/soc_sys_axi_gpio_0_0/soc_sys_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_sys_axi_gpio_0_0 || ORIG_REF_NAME==soc_sys_axi_gpio_0_0} -quiet] -quiet

# IP: bd/soc_sys/ip/soc_sys_xbar_0/soc_sys_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_sys_xbar_0 || ORIG_REF_NAME==soc_sys_xbar_0} -quiet] -quiet

# IP: bd/soc_sys/ip/soc_sys_ps7_0_axi_periph_0/soc_sys_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_sys_ps7_0_axi_periph_0 || ORIG_REF_NAME==soc_sys_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/soc_sys/ip/soc_sys_rst_ps7_0_100M_0/soc_sys_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_sys_rst_ps7_0_100M_0 || ORIG_REF_NAME==soc_sys_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/soc_sys/ip/soc_sys_axi_gpio_0_1/soc_sys_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_sys_axi_gpio_0_1 || ORIG_REF_NAME==soc_sys_axi_gpio_0_1} -quiet] -quiet

# IP: bd/soc_sys/ip/soc_sys_led_ip_0_0/soc_sys_led_ip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_sys_led_ip_0_0 || ORIG_REF_NAME==soc_sys_led_ip_0_0} -quiet] -quiet

# IP: bd/soc_sys/ip/soc_sys_axi_bram_ctrl_0_0/soc_sys_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_sys_axi_bram_ctrl_0_0 || ORIG_REF_NAME==soc_sys_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/soc_sys/ip/soc_sys_axi_bram_ctrl_0_bram_0/soc_sys_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_sys_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==soc_sys_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/soc_sys/ip/soc_sys_auto_pc_3/soc_sys_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_sys_auto_pc_3 || ORIG_REF_NAME==soc_sys_auto_pc_3} -quiet] -quiet

# IP: bd/soc_sys/ip/soc_sys_auto_pc_0/soc_sys_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_sys_auto_pc_0 || ORIG_REF_NAME==soc_sys_auto_pc_0} -quiet] -quiet

# IP: bd/soc_sys/ip/soc_sys_auto_pc_1/soc_sys_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_sys_auto_pc_1 || ORIG_REF_NAME==soc_sys_auto_pc_1} -quiet] -quiet

# IP: bd/soc_sys/ip/soc_sys_auto_pc_2/soc_sys_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_sys_auto_pc_2 || ORIG_REF_NAME==soc_sys_auto_pc_2} -quiet] -quiet

# XDC: d:/X_Project/X_Workspace/soc_lab3/soc_lab3.gen/sources_1/bd/soc_sys/ip/soc_sys_processing_system7_0_0/soc_sys_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_sys_processing_system7_0_0 || ORIG_REF_NAME==soc_sys_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/X_Project/X_Workspace/soc_lab3/soc_lab3.gen/sources_1/bd/soc_sys/ip/soc_sys_axi_gpio_0_0/soc_sys_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_sys_axi_gpio_0_0 || ORIG_REF_NAME==soc_sys_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/X_Project/X_Workspace/soc_lab3/soc_lab3.gen/sources_1/bd/soc_sys/ip/soc_sys_axi_gpio_0_0/soc_sys_axi_gpio_0_0_ooc.xdc

# XDC: d:/X_Project/X_Workspace/soc_lab3/soc_lab3.gen/sources_1/bd/soc_sys/ip/soc_sys_axi_gpio_0_0/soc_sys_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_sys_axi_gpio_0_0 || ORIG_REF_NAME==soc_sys_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/X_Project/X_Workspace/soc_lab3/soc_lab3.gen/sources_1/bd/soc_sys/ip/soc_sys_rst_ps7_0_100M_0/soc_sys_rst_ps7_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_sys_rst_ps7_0_100M_0 || ORIG_REF_NAME==soc_sys_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/X_Project/X_Workspace/soc_lab3/soc_lab3.gen/sources_1/bd/soc_sys/ip/soc_sys_rst_ps7_0_100M_0/soc_sys_rst_ps7_0_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_sys_rst_ps7_0_100M_0 || ORIG_REF_NAME==soc_sys_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/X_Project/X_Workspace/soc_lab3/soc_lab3.gen/sources_1/bd/soc_sys/ip/soc_sys_axi_gpio_0_1/soc_sys_axi_gpio_0_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_sys_axi_gpio_0_1 || ORIG_REF_NAME==soc_sys_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/X_Project/X_Workspace/soc_lab3/soc_lab3.gen/sources_1/bd/soc_sys/ip/soc_sys_axi_gpio_0_1/soc_sys_axi_gpio_0_1_ooc.xdc

# XDC: d:/X_Project/X_Workspace/soc_lab3/soc_lab3.gen/sources_1/bd/soc_sys/ip/soc_sys_axi_gpio_0_1/soc_sys_axi_gpio_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_sys_axi_gpio_0_1 || ORIG_REF_NAME==soc_sys_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/X_Project/X_Workspace/soc_lab3/soc_lab3.gen/sources_1/bd/soc_sys/ip/soc_sys_axi_bram_ctrl_0_bram_0/soc_sys_axi_bram_ctrl_0_bram_0_ooc.xdc

# XDC: d:/X_Project/X_Workspace/soc_lab3/soc_lab3.gen/sources_1/bd/soc_sys/ip/soc_sys_auto_pc_3/soc_sys_auto_pc_3_ooc.xdc

# XDC: d:/X_Project/X_Workspace/soc_lab3/soc_lab3.gen/sources_1/bd/soc_sys/ip/soc_sys_auto_pc_0/soc_sys_auto_pc_0_ooc.xdc

# XDC: d:/X_Project/X_Workspace/soc_lab3/soc_lab3.gen/sources_1/bd/soc_sys/ip/soc_sys_auto_pc_1/soc_sys_auto_pc_1_ooc.xdc

# XDC: d:/X_Project/X_Workspace/soc_lab3/soc_lab3.gen/sources_1/bd/soc_sys/ip/soc_sys_auto_pc_2/soc_sys_auto_pc_2_ooc.xdc

# XDC: D:/X_Project/X_Workspace/soc_lab3/soc_lab3.gen/sources_1/bd/soc_sys/soc_sys_ooc.xdc
